name: Upload files

on:
  push:
    branches: [ main ]
    paths:
    - upload/**

jobs:
  build:

    runs-on: [self-hosted, FIS-J, lolipop]

    steps:
    - uses: actions/checkout@v3

    - name: Upload files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER_URL }}
        username: ${{ secrets.FTP_USER_NAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./upload/
        server-dir: fis-j/
    - name: chmod remote files
      run: python3 .github/workflows/chmod_files.py ${{ secrets.FTP_SERVER_URL }} ${{ secrets.FTP_USER_NAME }} ${{ secrets.FTP_PASSWORD }} '/fis-j'
