name: Upload files

on:
  push:
    branches: [ main ]
    paths:
    - upload/**

env:
  LOCAL_TARGET_DIR: ./upload
  REMOTE_TARGET_DIR: web/airtote-d/
  SSH_PRIVATE_KEY_FILE: private.key

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: chmod normal files
      run: find ${{ env.LOCAL_TARGET_DIR }} -type f -not -name '*.sh' -exec chmod 604 {} ';'
    - name: chmod executable files
      run: find ${{ env.LOCAL_TARGET_DIR }} -type f -name '*.sh' -exec chmod 704 {} ';'

    - name: set private key value
      run: echo "$SSH_PRIVATE_KEY" > ${{ env.SSH_PRIVATE_KEY_FILE }}
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Upload files
      run: >
        rsync -av
        -e "ssh -i ${{ env.SSH_PRIVATE_KEY_FILE }} ${{ secrets.SSH_PORT_OPT_ARG }}"
        ${{ env.LOCAL_TARGET_DIR }}/
        ${{ secrets.SSH_USER_NAME }}@ssh.lolipop.jp:${{ env.REMOTE_TARGET_DIR }}
